apiVersion: apps/v1
kind: Deployment
metadata:
  name: csark-mvn-deploy
  labels:
    app: csark-mvn-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: csark-mvn-deploy
  template:
    metadata:
      labels:
        app: csark-mvn-deploy
    spec:
      containers:
      - name: csark-mvn-container
        image: csark/java-mvn-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: csark-mvn-np-service
  labels:
    app: csark-mvn-deploy
spec:
  selector:
    app: csark-mvn-deploy

  type: NodePort
  ports:
  - nodePort: 31200
    port: 8080
    targetPort: 8080
